#!/usr/bin/env python
import sys, os
try:
    from waflib.extras import symwaf2ic
    from waflib.extras.gtest import summary
    recurse = lambda *args: None # dummy recurse
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)

def depends(ctx):
    ctx('redman')
    ctx('redman', 'pyredman')

def options(opt):
    recurse(opt)
    opt.load('compiler_cxx')
    opt.load('gtest')
    opt.load('pytest')

def configure(cfg):
    recurse(cfg)
    cfg.load('compiler_cxx')
    cfg.load('gtest')
    cfg.load('pytest')

def build(bld):
    recurse(bld)

    bindings = ['redman_xml']

    bld(target          = 'redman-main',
        features        = 'cxx cxxprogram gtest',
        source          = bld.path.ant_glob('*.cpp'),
        install_path    = os.path.join('bin', 'tests'),
        use             = ['redman'] + bindings,
    )

    bld(tests           = [
            'pyredmantest.py',
            'pyredmanimporttest.py',
            ],
        target          = 'pyredman_tests',
        features        = 'pytest',
        use             = [ 'pyhalbe', 'pyredman' ] + bindings,
        install_path    = os.path.join('bin', 'tests'))

    datadirsrc = bld.path.find_dir('share')
    bld.install_files(
        '${PREFIX}/share',
        files=datadirsrc.ant_glob('**/*'),
        cwd=datadirsrc,
        relative_trick=True,
    )
