#!/usr/bin/env python
import os
try:
    from waflib.extras import symwaf2ic
    from waflib.extras.gtest import summary
    recurse = lambda *args: None
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)


def depends(ctx):
    ctx('redman')


def options(opt):
    recurse(opt)
    opt.load('compiler_cxx')
    opt.load('boost')


def configure(cfg):
    recurse(cfg)
    cfg.load('compiler_cxx')
    cfg.load('boost')

    cfg.check_boost(
        lib='filesystem serialization system',
        uselib_store='BOOST4REDMANXML'
    )


def build(bld):
    recurse(bld)

    flags = {
        'lib': [
            'dl',
        ]
    }

    bld.shlib(
        target='redman_xml',
        source=bld.path.ant_glob('*.cpp'),
        use=[
            'BOOST4REDMANXML',
            'redman',
        ],
        includes='.',
        install_path='lib',
        **flags
    )
